name: lint

on:
  push:
    branches:
      - trunk
    paths:
      - .github/workflows/build.yml
  pull_request:
    branches:
      - trunk
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      
      - name: "install shellcheck"
        uses: ludeeus/action-shellcheck@2.0.0
