name: build

on:
  push:
    branches:
      - trunk
    paths:
      - .github/workflows/build.yml
  pull_request:
    branches:
      - trunk
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      
      - name: "install shellcheck"
        run: apt install shellcheck

      - name: lint root dir
        run: shellcheck *.sh
      
      - name: lint contrib dir
        run: shellcheck contrib/*.sh
